vim.cmd("set expandtab")
vim.cmd("set tabstop=4")
vim.cmd("set softtabstop=4")
vim.cmd("set shiftwidth=4")
vim.cmd("set smarttab")
vim.cmd("set history=1000")
vim.cmd("set showmode")
vim.cmd("set autochdir")
vim.cmd("set paste")
vim.cmd("set nocompatible")
vim.cmd("set incsearch")
vim.cmd("set hlsearch")
vim.cmd("set smartcase")
vim.cmd("set ignorecase")
vim.cmd("set magic")
vim.cmd("set ai")
vim.cmd("set encoding=utf-8")
vim.cmd("set syntax=perl")
vim.cmd("set autowriteall")
vim.cmd("set sel=inclusive")
vim.cmd("set autoread")
vim.cmd("set nowritebackup")
vim.cmd("set noswapfile")
vim.cmd("set nobackup")
vim.cmd("filetype on")
vim.cmd("syntax on")
vim.cmd("filetype plugin on")
vim.cmd("filetype indent on")
vim.cmd("highlight WhitespaceEOL ctermbg=Red guibg=Red")
vim.cmd("nnoremap + <C-a>")
vim.cmd("nnoremap - <C-x>")

