####
# Config path: ~/.config/tailspin/config.toml 
####

[[regexps]]
regular_expression = '(creating index)'
style = { fg = "green" }

[[regexps]]
regular_expression = '(deleting index)'
style = { fg = "red" }

[[regexps]]
regular_expression = '(updating index)'
style = { fg = "yellow" }

