####
# Config path: ~/.config/tailspin/config.toml
####

[[keywords]]
words = ['creating index', 'updating index', 'Successfully completed', 'Successfully started', 'Successfully started Logstash', 'JVM bootstrap flags']
style = { fg = "green", italics = true }

[[keywords]]
words = ['Starting Logstash']
style = { fg = "yellow", italics = false }

[[regexps]]
regular_expression = '(Logstash (shut down|stopped)|shutting down|updating index|update_mapping|Successfully deleted|failed on|No config( ?uration| files)? found)'
style = { fg = "red", italics = true }
