# Load environment variables from ".env"
set dotenv-load

myos := if os() == "macos" {
    "macos"
} else if os() == "linux" {
    "linux"
} else if os() == "windows" {
    "windows"
} else {
    "null"
}


default:
    @just --list

# Exec all
all:
    @echo '[*]Executing all tasks. This might take longer..'
    @echo '[*]Done.'


# Verify pre-reqs
reqs:
    @echo 'eget/LinOrMacElseExit/tar/unzip/unrar/curl'

# Common utils (rg, rga, ugrep, rga, hypefine, )
tools_common:
    @echo '[*]Fetching utils for: {{myos}}'

#JSON
tools_json:
    @echo '[*]Fetching JSON utils..'

# Documentation
tools_docs:
    @echo '[*]Fetching mdbook, pandoc..'

# ProjectDiscovery
tools_infosec_projectdiscovery:
    @echo '[*]Fetching ProjectDiscovery (projectdiscovery.io) binaries..'

# InfoSec
tools_infosec:
    @echo 'termshark/wireshark/tcpreplay(linux)/vt/shodan/nrich/projectdiscovery'

# Data science
tools_datascience:
    @echo 'visidata/csvtk/q_csv'

